services:
  server:
    image: simple-news:${IMAGE_VERSION}
    build:
      context: .
      target: runner
    ports:
      - 3333:3333
    volumes:
      - ${DB_PATH}:/data
    environment:
      DATABASE_URL: sqlite:///data/${DB_FILE:-database.db}
      RUST_LOG: simple_news=debug,tower_http=debug,info
