name: reader

services:
  db:
    image: postgres:16
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  server:
    image: reader-server:latest
    build:
      context: .
      target: server
    ports:
      - 3333:3333
    volumes:
      - ./server:/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      SN_ADMIN_USER: ${SN_ADMIN_USER}
      SN_ADMIN_PASSWORD: ${SN_ADMIN_PASSWORD}

  web:
    image: reader-web:latest
    build:
      context: .
      target: web
    ports:
      - 3030:3000
    environment:
      API_HOST: http://server:3333

volumes:
  dbdata:
