name: simple-news

services:
  db:
    image: postgres:16
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  server:
    image: simple-news-server:latest
    build:
      context: server
      target: runner
    ports:
      - 3333:3333
    volumes:
      - ./server:/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      SN_ADMIN_USER: ${SN_ADMIN_USER}
      SN_ADMIN_PASSWORD: ${SN_ADMIN_PASSWORD}
      RUST_LOG: simple_news=debug,tower_http=debug,info

  app:
    image: simple-news-app:latest
    build:
      context: app
    ports:
      - 3000:3000
    environment:
      API_HOST: http://server:3333

volumes:
  dbdata:
