version: '3'

services:
  app:
    image: simple-news-app
    container_name: simple-news-app
    build:
      context: .
    command: ['node', 'index.js']
    ports:
      - '3000:3000'
    environment:
      DB_FILE: /db/data.db
    volumes:
      - .:/db

  downloader:
    image: simple-news-downloader
    container_name: simple-news-downloader
    build:
        context: .
        target: prebuild
    command: ['pnpm', 'download-feeds']
    environment:
      DB_FILE: /db/data.db
    volumes:
      - .:/db
