version: '3'

services:
  app:
    image: simple-news-app
    build:
      context: .
      target: app
    environment:
      DB_FILE: /db/data.db
      DB_MIGRATIONS: /app/migrations
    command: ['node', 'index.js']
    ports:
      - '3000:3000'
    volumes:
      - .:/db
      - ./migrations:/app/migrations
