version: '3'

services:
  app:
    image: simple-news-app
    container_name: simple-news-app
    restart: unless-stopped
    build:
      context: .
      target: app
    command: ['node', 'index.js']
    ports:
      - '3000:3000'
    environment:
      DB_FILE: /db/data.db
    volumes:
      - .:/db

  downloader:
    image: simple-news-downloader
    container_name: simple-news-downloader
    restart: unless-stopped
    build:
      context: .
      target: downloader
    command: ['node', 'scripts/download-feeds.js']
    environment:
      DB_FILE: /db/data.db
    volumes:
      - .:/db
