[package]
name = "sn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = "4.4.6"
reqwest = "0.11.22"
rpassword = "7.2.0"
serde_json = "1.0.107"
simple-news = { path = "../server" }
tokio = "1.32.0"
