services:
  server:
    image: simple-news:latest
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: runner
    ports:
      - 3333:3333
    volumes:
      - .:/data
    environment:
      DATABASE_URL: sqlite:///data/database.db
      RUST_LOG: simple_news=debug,tower_http=debug,info
