name: Test and Deploy
on:
  push:
    branches: [main]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - run: pnpm push
