name: Test and Deploy
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.2
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
